# Generated by Django 4.2.14 on 2024-08-02 14:28

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_short', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=200)),
                ('position_short', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['position_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_short', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_item', to='home.position')),
            ],
            options={
                'ordering': ['item_no'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_no', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_name', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('education', models.CharField(choices=[('Elementary', 'Elementary'), ('Secondary', 'Secondary'), ('College', 'College'), ('Graduated', 'College graduate'), ('Master', 'Master'), ('Doctor', 'Doctor')], default='Graduated', max_length=50)),
                ('date_hired', models.DateTimeField()),
                ('email_address', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('is_promoted', models.BooleanField()),
                ('is_cos', models.BooleanField()),
                ('is_permanent', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('picture', models.ImageField(upload_to=home.models.upload_to)),
                ('remarks', models.CharField(max_length=255)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_faculty', to='home.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_department', to='home.unit'),
        ),
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_promoted', models.DateTimeField(blank=True, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('item_status', models.CharField(choices=[('COS', 'COS'), ('Permanent', 'Permanent'), ('Vacant', 'Vacant')], default='COS', max_length=50)),
                ('is_active', models.BooleanField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_academicRank', to='home.faculty')),
                ('rank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_academicRank', to='home.item')),
            ],
        ),
    ]
