# Generated by Django 4.2.14 on 2024-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_department_short_department_department_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
