# Generated by Django 4.2.14 on 2024-08-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_item_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
