# Generated by Django 4.2.14 on 2024-08-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faculty_contact_no_alter_faculty_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_cos',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_permanent',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_promoted',
        ),
    ]
