# Generated by Django 4.2.14 on 2024-08-04 07:54

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_faculty_is_cos_remove_faculty_is_permanent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_to),
        ),
    ]
