# Generated by Django 4.2.14 on 2024-08-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_faculty_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrank',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='date_promoted',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='item_status',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='rank_id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_promoted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='item_status',
            field=models.CharField(choices=[('COS', 'COS'), ('Permanent', 'Permanent'), ('Vacant', 'Vacant')], default='COS', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='rank_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rank_academicRank', to='home.item'),
            preserve_default=False,
        ),
    ]
