# Generated by Django 4.2.14 on 2024-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_faculty_department_id_alter_faculty_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_hired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
