# Generated by Django 4.2.14 on 2024-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_faculty_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='item_status',
            field=models.CharField(choices=[('COS', 'COS'), ('Permanent', 'Permanent'), ('Vacant', 'Vacant')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
