# Generated by Django 4.2.14 on 2024-08-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_item_options_remove_faculty_rank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_hired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='education',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('Secondary', 'Secondary'), ('College', 'College'), ('Master', 'Master'), ('Doctor', 'Doctor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employment_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], default='Teaching', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_item', to='home.position'),
        ),
    ]
