# Generated by Django 4.2.14 on 2024-08-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_faculty_is_promoted_alter_faculty_date_hired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Administrative', 'Adminisrative')], default='Academic', max_length=50),
        ),
    ]
